---
title: "Regresión Logística"
author: "Mario Becerra C"
date: "24/05/2015"
output: html_document
---

```{r}
library(glmnet)
library(caret)
```


```{r, eval=FALSE}
load('../data/TF_Erick.RData')
write.csv(data_train, file='../data/data_train.csv', row.names=FALSE)
write.csv(data_test, file='../data/data_test.csv', row.names=FALSE)
```
```{r}
colTypes <- c('factor', 'factor', 'factor', 'integer', 'integer', 'numeric', 'numeric', 'numeric', 'numeric', 'numeric', 'numeric', 'numeric', 'numeric', 'numeric', 'numeric', 'factor', 'numeric', 'integer', 'factor', 'factor', 'factor', 'factor', 'factor', 'factor', 'character', 'character', 'factor', 'factor', 'factor', 'factor', 'factor', 'factor')
train <- read.csv('../data/data_train.csv', colClasses=colTypes)
test <- read.csv('../data/data_test.csv', colClasses=colTypes)
```


```{r, eval=FALSE}
xfactors <- model.matrix(Dependiente ~ Tipo.de.declaratoria + Tipo.de.fenomeno + GM + R_Inun + R_Hur + R_Des + R_Seq + R_IF + R_Den +  a_o + Clave.del.Estado + Municipio, data=train)[,-1]

x <- cbind(data.frame(train$ANAL, train$SPRI, train$OVSDS, train$OVSEE, train$OVSAE, train$VHAC, train$OVPT, train$PL.5000, train$PO2SM, train$IM, train$area_mun..ha.), xfactors)

x_m <- as.matrix(x[complete.cases(x),])

mod.1 <- cv.glmnet(x = x_m, y = train$Dependiente[complete.cases(x)], alpha=0.5, family='binomial')
save(mod.1, file='../data/mod.1.RData')
```

```{r}
load('../data/mod.1.RData')
levels(test$Tipo.de.declaratoria) <- levels(train$Tipo.de.declaratoria)
levels(test$Tipo.de.fenomeno) <- levels(train$Tipo.de.fenomeno)
levels(test$GM) <- levels(train$GM)
levels(test$R_Inun) <- levels(train$R_Inun)
levels(test$R_Hur) <- levels(train$R_Hur)
levels(test$R_Des) <- levels(train$R_Des)
levels(test$R_Seq) <- levels(train$R_Seq)
levels(test$R_IF) <- levels(train$R_IF)
levels(test$R_Den) <- levels(train$R_Den)
levels(test$a_o) <- levels(train$a_o)
levels(test$Clave.del.Estado) <- levels(train$Clave.del.Estado)
levels(test$Municipio) <- levels(train$Municipio)

test2 <- test[complete.cases(test),]

xfactors_test <- model.matrix(Dependiente ~ Tipo.de.declaratoria + Tipo.de.fenomeno + GM + R_Inun + R_Hur + R_Des + R_Seq + R_IF + R_Den +  a_o + Clave.del.Estado + Municipio, data=test2)[,-1]

x_num <- data.frame(test2$ANAL, test2$SPRI, test2$OVSDS, test2$OVSEE, test2$OVSAE, test2$VHAC, test2$OVPT, test2$PL.5000, test2$PO2SM, test2$IM, test2$area_mun..ha.)

xnew<- as.matrix(cbind(x_num, xfactors_test))

predicted.1 <- predict(mod.1, xnew, type="response")
predicted.class <- as.factor(predicted.1>0.1)
levels(predicted.class) <- c(0,1)
confusionMatrix(predicted.class, test2$Dependiente)
```

